apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/mintmaker/config/default?ref=8d903c345b6c374bd14d5878aa3eb5db93968e48
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=8d903c345b6c374bd14d5878aa3eb5db93968e48

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 8d903c345b6c374bd14d5878aa3eb5db93968e48
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: d4650cac8ced9faf23cf8fd2285df557adbb45e0

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - path: manager_patch.yaml

configurations:
- kustomizeconfig.yaml
